### ISSUE TITLE
Questions about discrepancy loss

### ISSUE THREAD

**Issue by whb919168848** [Wu0409/DuPL#3]
Thank you very much for your previous answer. I found that the discrepancy loss in code is diffrent from which in your paper.Which one is right?

**Comment by whb919168848** [comment]
@Wu0409

**Comment by Wu0409** [comment]
Thank you for your attention. Both implementations are ok :)

When we released this repository, we tested the direct use of `1 + cos(a, b)` and found that it achieved very close performance. For simplicity, we choose `1 + cos(a, b)` as the final implementation of `sim_loss`.

In fact, the goal of Equation (2) in the paper is quite similar to `1 + cos(a, b)` (except for the penalty associated with using the `log` operator).

**Comment by Wu0409** [comment]
no further updates.
