### ISSUE TITLE
custom dataset question

### ISSUE THREAD

**Issue by chenruipeng123** [Wu0409/DuPL#4]
Hi Dear Author, I want to use custom dataset for training, but my custom dataset doesn't have img_box, but your code is based on voc or coco dataset for training, it is covering img_box, how do I need to change the code?

**Comment by Wu0409** [comment]
Hey, thank you for your interest in our project! 😊

DuPL is trained entirely using image-level labels without any bounding box information. The img_box you mentioned likely refers to the boxes obtained through augmentation strategies. We use the crop box to filter out regions that do not belong to the image.

To quickly adapt to custom datasets, you can use VOC-style annotations or customize the data pipeline.

Feel free to reach out if you have any other questions.

**Comment by Wu0409** [comment]
no further updates.
