### ISSUE TITLE
Regarding the issue of reproducing results

### ISSUE THREAD

**Issue by InMyDreammer** [Wu0409/DuPL#6]
Dear Author,
[train.log](https://github.com/user-attachments/files/17338682/train.log)
I have followed your experimental setup and trained the model, but the final results are significantly different from those reported in your paper and log files. Below is my training log file for your reference.

**Comment by Wu0409** [comment]
Hey, thank you for your interest in our project! 😊

I have checked the training log, and it seems that the experiment setting should be **correct**. 

What I can confirm is that the initialization of the dual student does have an impact on final segmentation results, so randomness may cause some performance gaps, but not as much as 2% 😣. 

If possible, can you modify the random seed to see if there is a change in the performance gap?

**Comment by InMyDreammer** [comment]
Hello, I would like to ask where I can find the semantic segmentation results from Table 2 in your paper within the training log? Are they the results in the Seg_1 or Seg_2 columns? However, the results in these two columns differ significantly from those in the paper. Or do I need to run the evaluation script to obtain the semantic segmentation results?

**Comment by Wu0409** [comment]
> Hello, I would like to ask where I can find the semantic segmentation results from Table 2 in your paper within the training log? Are they the results in the Seg_1 or Seg_2 columns? However, the results in these two columns differ significantly from those in the paper. Or do I need to run the evaluation script to obtain the semantic segmentation results?

Hey, the results in Table 2 are the final segmentation results, which are post-processed by dCRF. 

The segmentation results in the training log are original predictions, you can run the evaluation script to post-process the predictions and get the final results, as you mentioned.

PS: the VOC test set need be evaluated by the official server.
