### ISSUE TITLE
test exception

### ISSUE THREAD

**Issue by geek-APTX4869** [Wu0409/DuPL#8]
Dear author：
  在评估服务器上传后，一直处于`Evaluation in progress`的状态

**Comment by Wu0409** [comment]
你好，通常 VOC 验证服务器提交，数分钟就可以返回结果。如果一直 Evaluation in progress，过段时间再测试看看。

Hey, usually the VOC verification server will return the result within a few minutes after submission. If it keeps showing "Evaluation in progress", please test again after a while.

**Comment by Wu0409** [comment]
No further update.

**Comment by Minorant** [comment]
请问您成功测试了吗
