### ISSUE TITLE
nan problem

### ISSUE THREAD

**Issue by Yuki2L0ve** [Wu0409/DuPL#9]
Thank you for opening the source code. I'm a beginner. I am trying to reproduce your paper. I followed your tutorial and ran the following line of code：
```shell
python -m torch.distributed.launch --nproc_per_node=4 eval_seg_coco_ddp.py --data_folder [../MSCOCO/coco2014] --label_folder [../MSCOCO/SegmentationClass] --model_path [path_to_model]
```

I got four files, namely, results_0.log~results_3.log. I found that the mIoU result in results_3.log is nan. can the author please tell me the reason? Thank you very much.
![image](https://github.com/user-attachments/assets/a61b9e00-a38f-4c2d-8849-7b4104d7d665)

**Comment by Wu0409** [comment]
Hey! Thanks for your interests of our work :)

For CoCo, we split the evaluation dataset for N subsets (depends on the number of your GPUs) for faster inference. Therefore, some long-tailed categories may not exist in some subsets (as you can see the performance of `hair drier` is `0` of your set \#3). This causes the mIoU calculation becomes nan.

Don't worry about this, `results_1.log~results_3.log` are just the temporary inference logs and the final results will be recorded in [results_0.log (Rank 0)](https://github.com/Wu0409/DuPL/blob/main/tools/eval_seg_coco_ddp.py#L250-L256) after CRF post-processing.

**Comment by Yuki2L0ve** [comment]
Thank you very much. I got it. Also, I have some questions：

First problem:
when I've run the code:
```shell
# For Pascal VOC
python eval_seg_voc.py --data_folder [../VOC2012] --model_path [path_to_model]
```
I got `seg_preds_rgb` file:
![image](https://github.com/user-attachments/assets/e1275ae9-532e-486d-b53a-537dfd44200d)
So is it not necessary to run the following line of code? Because I found that the rgb images generated by running this line of code and the rgb images in the `seg_preds_rgb` file all seem to be the same.
```shell
# modify the "dir" and "target_dir" before running
python convert_voc_rgb.py
```

Second Problem:
If I need to convert rgb segmentation labels for the official VOC evaluation, I don't find `convert_voc_rgb.py`. I just found `DuPL/tools/convert_test_seg.py`?
And then in `convert_test_seg.py`:
```python
    dir = './work_dir_voc_wseg/2023-09-26-21-50-19-319439_train_voc/segs/seg_preds/test/'  # an example
    target_dir = './work_dir_voc_wseg/2023-09-26-21-50-19-319439_train_voc/segs/convert/test/'
```
But In my directory, I only see val, not test, as shown above pictures.  So maybe it should be `val` instead of `test`?

Third Problem:
In `infer_cam_voc.py`,  the `from model.model_seg_neg_v6_4_14 import siamese_network` maybe `from model.model_dupl import siamese_network` ?

Looking forward to your reply. Thank you very much.

**Comment by Wu0409** [comment]
#### For your first confusion:
You are correct that the RGB images generated by running this line of code and the RGB images in the seg_preds_rgb file appear to be identical. The reason for running `convert_test_seg.py` is that we encountered some issues with the VOC evaluation server when evaluating the original outputs in `seg_preds_rgb`—likely related to image encoding (though I'm not entirely certain). As a result, we re-converted the outputs using this script for submission to the evaluation server. If your goal is simply to visualize the predictions, there is no difference in appearance.

#### For your second confusion:
I apologize for my oversight. It should indeed be `convert_test_seg.py`. This script, as mentioned above, is specifically for evaluation on the official VOC evaluation server. By default, evaluation on the VOC `eval` set does not need to be conducted on the server. If you wish to obtain predictions for the `test` set and convert them for the evaluation server, you need to set the `test` configuration [(here)](https://github.com/Wu0409/DuPL/blob/main/tools/eval_seg_voc.py#L26) in` eval_seg_voc.py` and run the script first.

#### For your third confusion:
Correct, and thank you for pointing this out :). I will update the scripts later.

**Comment by Yuki2L0ve** [comment]
Thank you for your reply！😊 It really help!

**Comment by Wu0409** [comment]
> Thank you for your reply！😊 It really help!

Feel free to ask if you have any questions or confusion.
